"""Call Analysis Table updated

Revision ID: 2b70b95c1f04
Revises: a36bb5aa0970
Create Date: 2025-09-12 16:13:17.157269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b70b95c1f04'
down_revision: Union[str, Sequence[str], None] = 'a36bb5aa0970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'call_analysis', ['call_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'call_analysis', type_='unique')
    # ### end Alembic commands ###
