"""Create conversations table 

Revision ID: 446691919631
Revises: 20945bc23aba
Create Date: 2025-09-04 06:13:24.466377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '446691919631'
down_revision: Union[str, Sequence[str], None] = '20945bc23aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_message', sa.TEXT(), nullable=False),
    sa.Column('ai_response', sa.TEXT(), nullable=False),
    sa.Column('Procesing_time', sa.FLOAT(), nullable=False),
    sa.Column('audio_duration', sa.FLOAT(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('confidenece_score', sa.FLOAT(), nullable=True),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('customer_tier', sa.String(length=50), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversations')
    # ### end Alembic commands ###
