"""Add sentiment columns to call_analysis

Revision ID: 54fc84054a80
Revises: 89f0862ab29f
Create Date: 2025-09-12 15:30:25.706242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54fc84054a80'
down_revision: Union[str, Sequence[str], None] = '89f0862ab29f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_analysis', sa.Column('conversation', sa.Text(), nullable=True))
    op.add_column('call_analysis', sa.Column('cx_neutral_percentage', sa.Float(), nullable=True))
    op.add_column('call_analysis', sa.Column('cx_positive_percentage', sa.Float(), nullable=True))
    op.add_column('call_analysis', sa.Column('cx_negative_percentage', sa.Float(), nullable=True))
    op.add_column('call_analysis', sa.Column('overall_call_sentiment', sa.String(length=20), nullable=True))
    op.drop_column('call_analysis', 'analysis_result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_analysis', sa.Column('analysis_result', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('call_analysis', 'overall_call_sentiment')
    op.drop_column('call_analysis', 'cx_negative_percentage')
    op.drop_column('call_analysis', 'cx_positive_percentage')
    op.drop_column('call_analysis', 'cx_neutral_percentage')
    op.drop_column('call_analysis', 'conversation')
    # ### end Alembic commands ###
