"""Create systemMetrics table

Revision ID: 98fbcc307b47
Revises: 446691919631
Create Date: 2025-09-04 06:44:02.332522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fbcc307b47'
down_revision: Union[str, Sequence[str], None] = '446691919631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cpu_usage', sa.FLOAT(), nullable=False),
    sa.Column('memory_usage', sa.FLOAT(), nullable=False),
    sa.Column('gpu_usage', sa.FLOAT(), nullable=True),
    sa.Column('active_connections', sa.Integer(), nullable=True),
    sa.Column('request_per_minutes', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.FLOAT(), nullable=True),
    sa.Column('error_rate', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_id'), 'system_metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_metrics_id'), table_name='system_metrics')
    op.drop_table('system_metrics')
    # ### end Alembic commands ###
