"""Add sentiment columns to call_analysis

Revision ID: a36bb5aa0970
Revises: 54fc84054a80
Create Date: 2025-09-12 15:33:21.693216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36bb5aa0970'
down_revision: Union[str, Sequence[str], None] = '54fc84054a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_analysis', sa.Column('customer_dialogs', sa.Text(), nullable=True))
    op.add_column('call_analysis', sa.Column('agent_dialogs', sa.Text(), nullable=True))
    op.drop_column('call_analysis', 'conversation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_analysis', sa.Column('conversation', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('call_analysis', 'agent_dialogs')
    op.drop_column('call_analysis', 'customer_dialogs')
    # ### end Alembic commands ###
