"""Create AudioSessions table

Revision ID: e6def0beebc8
Revises: 98fbcc307b47
Create Date: 2025-09-04 23:41:34.223614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6def0beebc8'
down_revision: Union[str, Sequence[str], None] = '98fbcc307b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiosessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('total_duration', sa.FLOAT(), server_default='0.0', nullable=True),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audiosessions')
    # ### end Alembic commands ###
