"""Create callanalytics table

Revision ID: eede0f4795d2
Revises: bb10d92df89f
Create Date: 2025-09-05 00:45:38.346368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eede0f4795d2'
down_revision: Union[str, Sequence[str], None] = 'bb10d92df89f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('sentiment_trend', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('speaker_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('intent_classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('urgency_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compliance_score', sa.FLOAT(), nullable=True),
    sa.Column('resolution_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_analytics')
    # ### end Alembic commands ###
