"""Create genesys_calls table

Revision ID: ef5671fb573e
Revises: eede0f4795d2
Create Date: 2025-09-05 01:56:35.526883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef5671fb573e'
down_revision: Union[str, Sequence[str], None] = 'eede0f4795d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genesys_calls ',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('participant_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('customer_number', sa.String(length=50), nullable=True),
    sa.Column('agent_id', sa.String(length=255), nullable=True),
    sa.Column('queue_name', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('ani', sa.String(length=50), nullable=True),
    sa.Column('dnis', sa.String(length=50), nullable=True),
    sa.Column('customer_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('call_analytics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genesys_calls ')
    # ### end Alembic commands ###
